CREATE TABLE [||PRE||mg_display] ([displayID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[displayTypeID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[objectID] NVARCHAR(35) NULL  DEFAULT NULL  ,[name] VARCHAR(150) NOT NULL  DEFAULT NULL  ,[dateCreate] DATETIME NOT NULL  DEFAULT NULL  ,[dateLastUpdate] DATETIME NOT NULL  DEFAULT NULL  ,[siteID] VARCHAR(25) NOT NULL  DEFAULT NULL  ,[params] NTEXT NULL  DEFAULT NULL  ,[notes] NTEXT NULL  DEFAULT NULL  ,[isActive] SMALLINT NULL  DEFAULT 0 ,[adminID] NVARCHAR(35) NULL  DEFAULT NULL  ,[moduleID] NVARCHAR(35) NULL  DEFAULT NULL  ,[contentID] NVARCHAR(35) NULL  DEFAULT NULL  ,[isValid] SMALLINT NULL  DEFAULT 0 ,[settings] NTEXT NULL  DEFAULT NULL  ,CONSTRAINT [||PRE||mg_display_||PRE||mg_display_PRIMARY]  PRIMARY KEY  CLUSTERED  ([displayID])); 

CREATE TABLE [||PRE||mg_displayimage] ([displayImageID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[displayID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[imageID] NVARCHAR(35) NULL  DEFAULT NULL  ,[isProcessed] SMALLINT NULL  DEFAULT 0 ,[isValid] SMALLINT NULL  DEFAULT 0 ,[fileID] NVARCHAR(35) NULL  DEFAULT NULL  ,[attempts] SMALLINT NULL  DEFAULT 0 ,[processDate] DATETIME NULL  DEFAULT NULL  ,[isProcessingID] NVARCHAR(35) NULL  DEFAULT NULL  ,[dateCreate] DATETIME NOT NULL  DEFAULT NULL  ,[dateLastUpdate] DATETIME NOT NULL  DEFAULT NULL  ,[isExternal] SMALLINT NOT NULL  DEFAULT 0 ,[linkURL] VARCHAR(150) NULL  DEFAULT NULL  ,[isMuraGallery] SMALLINT NULL  DEFAULT 0 ,CONSTRAINT [||PRE||mg_displayimage_||PRE||mg_displayimage_PRIMARY]  PRIMARY KEY  NONCLUSTERED  ([displayImageID])); 
 CREATE  UNIQUE  INDEX [||PRE||mg_displayimage_||PRE||mg_displayimage_idxDisplayImage] ON [||PRE||mg_displayimage] ([displayID],[imageID]);

CREATE TABLE [||PRE||mg_displaytype] ([displaytypeid] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[objectID] NVARCHAR(35) NULL  DEFAULT NULL  ,[package] VARCHAR(45) NOT NULL  DEFAULT NULL  ,[name] VARCHAR(45) NOT NULL  DEFAULT NULL  ,[description] NTEXT NULL  DEFAULT NULL  ,[settings] NTEXT NULL  DEFAULT NULL  ,[isConfigurable] SMALLINT NOT NULL  DEFAULT 0 ,[isActive] SMALLINT NOT NULL  DEFAULT 0 ,[version] VARCHAR(12) NOT NULL  DEFAULT NULL  ,[defaults] NTEXT NULL  DEFAULT NULL  ,[moduleID] NVARCHAR(35) NULL  DEFAULT NULL  ,CONSTRAINT [||PRE||mg_displaytype_||PRE||mg_displaytype_PRIMARY]  PRIMARY KEY  NONCLUSTERED  ([displaytypeid])); 

CREATE TABLE [||PRE||mg_image] ([imageID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[fileID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[caption] VARCHAR(150) NULL  DEFAULT NULL  ,[description] NTEXT NULL  DEFAULT NULL  ,[tags] VARCHAR(255) NULL  DEFAULT NULL  ,[categoryID] NVARCHAR(35) NULL  DEFAULT NULL  ,[dateCreate] DATETIME NOT NULL  DEFAULT NULL  ,[dateLastUpdate] DATETIME NOT NULL  DEFAULT NULL  ,[siteID] VARCHAR(45) NOT NULL  DEFAULT NULL  ,[linkURL] VARCHAR(150) NULL  DEFAULT NULL  ,[friendlyName] VARCHAR(150) NULL  DEFAULT NULL  ,[isActive] SMALLINT NOT NULL  DEFAULT 0 ,[type] VARCHAR(10) NULL  DEFAULT NULL  ,[adminID] NVARCHAR(35) NULL  DEFAULT NULL  ,[summary] NTEXT NULL  DEFAULT NULL  ,[name] VARCHAR(150) NULL  DEFAULT NULL  ,[remoteID] NVARCHAR(35) NULL  DEFAULT NULL  ,CONSTRAINT [||PRE||mg_image_||PRE||mg_image_PRIMARY]  PRIMARY KEY  NONCLUSTERED  ([imageID])); 

CREATE TABLE [||PRE||mg_imagegroup] ([imageGroupID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[name] VARCHAR(145) NOT NULL  DEFAULT NULL  ,[description] VARCHAR(255) NULL  DEFAULT NULL  ,[dateCreate] DATETIME NOT NULL  DEFAULT NULL  ,[dateLastUpdate] DATETIME NOT NULL  DEFAULT NULL  ,[adminID] NVARCHAR(45) NULL  DEFAULT NULL  ,[tags] VARCHAR(255) NULL  DEFAULT NULL  ,[siteID] VARCHAR(45) NOT NULL  DEFAULT NULL  ,[isActive] SMALLINT NOT NULL  DEFAULT 0 ,CONSTRAINT [||PRE||mg_imagegroup_||PRE||mg_imagegroup_PRIMARY]  PRIMARY KEY  NONCLUSTERED  ([imageGroupID])); 

CREATE TABLE [||PRE||mg_imagegroupimage] ([imageGroupID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[imageID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[caption] VARCHAR(255) NULL  DEFAULT NULL  ,[description] NTEXT NULL  DEFAULT NULL  ,[imageClass] VARCHAR(25) NULL  DEFAULT NULL  ,[textClass] VARCHAR(25) NULL  DEFAULT NULL  ,[orderNo] BIGINT NOT NULL  DEFAULT 0 ,CONSTRAINT [||PRE||mg_imagegroupimage_||PRE||mg_imagegroupimage_PRIMARY]  PRIMARY KEY  NONCLUSTERED  ([imageGroupID],[imageID])); 
 CREATE  INDEX [||PRE||mg_imagegroupimage_||PRE||mg_imagegroupimage_idxOrderNo] ON [||PRE||mg_imagegroupimage] ([orderNo]);

CREATE TABLE [||PRE||mg_setting] ([settingsID] NVARCHAR(35) NOT NULL  DEFAULT NULL  ,[siteID] VARCHAR(25) NOT NULL  DEFAULT NULL  ,[dateCreate] DATETIME NOT NULL  DEFAULT NULL  ,[dateLastUpdate] DATETIME NOT NULL  DEFAULT NULL  ,[isMaster] SMALLINT NOT NULL  DEFAULT NULL  ,[imageWidth] BIGINT NOT NULL  DEFAULT 0 ,[imageHeight] BIGINT NOT NULL  DEFAULT 0 ,[imageWidthMedium] BIGINT NOT NULL  DEFAULT 0 ,[imageHeightMedium] BIGINT NOT NULL  DEFAULT 0 ,[imageWidthSmall] BIGINT NOT NULL  DEFAULT 0 ,[imageHeightSmall] BIGINT NOT NULL  DEFAULT 0 ,[imageResizeType] VARCHAR(45) NOT NULL  DEFAULT N'Resize' ,[imageAspectType] VARCHAR(45) NOT NULL  DEFAULT N'AspectX' ,[imageQualityType] VARCHAR(45) NOT NULL  DEFAULT N'highestQuality' ,[imageResizeTypeMedium] VARCHAR(45) NOT NULL  DEFAULT N'CropResize' ,[imageAspectTypeMedium] VARCHAR(45) NOT NULL  DEFAULT N'Square' ,[imageQualityTypeMedium] VARCHAR(45) NOT NULL  DEFAULT N'mediumQuality' ,[imageResizeTypeSmall] VARCHAR(45) NOT NULL  DEFAULT N'CropResize' ,[imageAspectTypeSmall] VARCHAR(45) NOT NULL  DEFAULT N'Square' ,[imageQualityTypeSmall] VARCHAR(45) NOT NULL  DEFAULT N'mediumQuality' ,[imageCropType] VARCHAR(45) NOT NULL  DEFAULT N'BestXY' ,[imageCropTypeMedium] VARCHAR(45) NOT NULL  DEFAULT N'BestXY' ,[imageCropTypeSmall] VARCHAR(45) NOT NULL  DEFAULT N'BestXY' ,[defaultDisplayTypeID] NVARCHAR(35) NULL  DEFAULT NULL  ,[fileSizeLimit] BIGINT NOT NULL  DEFAULT 0 ,[SyncInfo] SMALLINT NOT NULL  DEFAULT 0 ,CONSTRAINT [||PRE||mg_setting_||PRE||mg_setting_PRIMARY]  PRIMARY KEY  NONCLUSTERED  ([settingsID])); 

INSERT INTO [||PRE||mg_displaytype] ([displaytypeid],[objectID],[package],[name],[description],[settings],[isConfigurable],[isActive],[version],[defaults],[moduleID]) VALUES (N'095DE279-1D6B-4BC2-B85B85203322F805',NULL,N'galleryview',N'Gallery View (jQuery)',N'Creates a ''GalleryView'' jQuery gallery with film strip',N'{"requiresImageGroup":true}',1,1,N'1.0',N'{"thumbwidth":50,"thumbheight":50,"imagewidth":600,"imageheight":450,"thumbresizetype":"crop","resizetype":"cropresize","aspecttype":"AspectXY","showCaption":"false","showDescription":"true","panels":"true","filmstrip":"true","speed":750,"interval":8000,"overlaypos":"bottom","overlayheight":80}',NULL);
INSERT INTO [||PRE||mg_displaytype] ([displaytypeid],[objectID],[package],[name],[description],[settings],[isConfigurable],[isActive],[version],[defaults],[moduleID]) VALUES (N'7AB6608A-9BF3-45DC-BD7963F76629EBD8',NULL,N'cycle',N'Cycle (jQuery)',N'Multiple transition effects and formats',N'{"requiresImageGroup":true}',1,1,N'1.0',N'{"resizetype":"cropresize","style":"dotnav","interval":"5000","speed":"500","aspecttype":"AspectX","imageheight":"450","imagewidth":"600","pauseonnav":"1","effect":"fade"}',NULL);
INSERT INTO [||PRE||mg_displaytype] ([displaytypeid],[objectID],[package],[name],[description],[settings],[isConfigurable],[isActive],[version],[defaults],[moduleID]) VALUES (N'E4277F8F-BE07-4788-987F97A33E1AA4EE',NULL,N'popeye',N'PopEye Gallery (jQuery)',N'Creates a PopEye jQuery gallery',N'{"requiresImageGroup":true}',1,1,N'1.0',N'{"thumbheight":"200","aspecttype":"AspectX","imageheight":"400","showcaption":"true","imagewidth":"400","direction":"right","resizetype":"cropresize","thumbwidth":"200"}',NULL);
INSERT INTO [||PRE||mg_displaytype] ([displaytypeid],[objectID],[package],[name],[description],[settings],[isConfigurable],[isActive],[version],[defaults],[moduleID]) VALUES (N'F72E1EA3-3CEE-4613-B2E6B5BBB0807DF0',NULL,N'shadowbox',N'ShadowBox',N'Creates a Mura-style gallery with ShadowBox component',N'{"requiresImageGroup":true}',1,1,N'1.0',N'{"showname":"true","thumbheight":"100","aspecttype":"AspectXY","imageheight":"450","showcaption":"false","imagewidth":"600","resizetype":"cropresize","thumbwidth":"100"}',NULL);

INSERT INTO [||PRE||mg_setting] ([settingsID],[siteID],[dateCreate],[dateLastUpdate],[isMaster],[imageWidth],[imageHeight],[imageWidthMedium],[imageHeightMedium],[imageWidthSmall],[imageHeightSmall],[imageResizeType],[imageAspectType],[imageQualityType],[imageResizeTypeMedium],[imageAspectTypeMedium],[imageQualityTypeMedium],[imageResizeTypeSmall],[imageAspectTypeSmall],[imageQualityTypeSmall],[imageCropType],[imageCropTypeMedium],[imageCropTypeSmall],[defaultDisplayTypeID],[fileSizeLimit],[SyncInfo]) VALUES (N'00000001-0001-0001-0000000000000001',N'default',N'2010-09-02 01:04:16',N'2011-01-08 14:38:07',0,1200,900,200,200,40,40,N'resize',N'AspectX',N'highestQuality',N'cropresize',N'',N'mediumQuality',N'cropresize',N'',N'mediumQuality',N'BestXY',N'BestXY',N'BestXY',N'095DE279-1D6B-4BC2-B85B85203322F805',5000,0);
